name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  frontend:
    name: Biome + Unitest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.2

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install deps
        run: pnpm 

      - name: Biome (check)
        run: pnpm format

      - name: Unitest (Vitest)
        run: pnpm test
